package ru.yandex.practicum.filmorate.dao.mapper;

import org.springframework.jdbc.core.RowMapper;
import ru.yandex.practicum.filmorate.model.Event;
import ru.yandex.practicum.filmorate.model.EventOperation;
import ru.yandex.practicum.filmorate.model.EventType;
import ru.yandex.practicum.filmorate.model.User;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.Instant;

public class EventRowMapper implements RowMapper<Event> {
    @Override
    public Event mapRow(ResultSet rs, int rowNum) throws SQLException {
        return Event.builder()
                .eventId(rs.getInt("event_id"))
                .timestamp((rs.getLong("timestamp")))
                .userId(rs.getInt("user_id"))
                .eventType(EventType.valueOf(rs.getString("event_type")))
                // .eventType(rs.getObject("event_type", EventType.class))
                .operation(EventOperation.valueOf(rs.getString("operation")))
                // .eventOperation(rs.getObject("operation", EventOperation.class))
                .entityId(rs.getInt("entity_id"))
                .build();
    }
}
/*
  event_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer REFERENCES users (user_id) ON DELETE CASCADE,
  event_type varchar NOT NULL,
  operation varchar NOT NULL,
  timestamp timestamp NOT NULL,
  entity_id integer NOT NULL*/